name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump_version
        run: echo "::set-output name=version::$(npm run version:bump --silent)"

      - name: Check if version changed
        id: version_changed
        run: |
          git diff --exit-code --quiet -- package.json
          echo ::set-output name=changed::$?

      - name: Commit version bump
        if: steps.version_changed.outputs.changed == '0'
        run: |
          VERSION=${{ steps.bump_version.outputs.version }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "chore: bump version to $VERSION"
          echo "Committed version bump to Git"

      - name: Push changes
        if: steps.version_changed.outputs.changed == '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
