name: Angular Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Check for changes in auth library
        id: auth-check
        run: |
          cd projects/auth
          if git diff-index --quiet HEAD --; then echo "::set-output name=changed::false"; else echo "::set-output name=changed::true"; fi
      - name: Check for changes in util library
        id: util-check
        run: |
          cd projects/util
          if git diff-index --quiet HEAD --; then echo "::set-output name=changed::false"; else echo "::set-output name=changed::true"; fi
      - name: Upload distribution folders
        if: steps.auth-check.outputs.changed == 'true' || steps.util-check.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./dist/auth
            ./dist/util

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download distribution folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish auth library
        if: steps.auth-check.outputs.changed == 'true'
        run: npm publish ./dist/auth --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish util library
        if: steps.util-check.outputs.changed == 'true'
        run: npm publish ./dist/util --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
