name: Build and Publish Angular Libraries

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Build Libraries
        run: npm run build:auth

      - name: Publish Libraries to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          cd ./dist
          for dir in */ ; do
            cd $dir
            npm version patch
            npm publish --access public --registry=https://npm.pkg.github.com/ --scope=@avs2001/auth
            cd ..
          done
