name: Angular Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build:util
      - run: npm run build:auth
      - name: Upload distribution folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./dist/auth
            ./dist/util

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download distribution folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish auth library
        run: npm publish ./dist/auth --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish auth library
        run: npm publish ./dist/auth --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish ui library
        run: npm publish ./dist/ui --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
