name: Angular Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build:util
      - run: npm run build:auth
      - name: Upload distribution folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./dist/auth
            ./dist/util

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check for changes in auth library
        run: |
          changed_files="$(git diff --name-only HEAD^ HEAD)"
          if echo "$changed_files" | grep -q "^projects/auth/"; then
            echo "Code for auth library has changed."
          else
            echo "Code for auth library has not changed. Skipping publish."
            exit 1
          fi
      - name: Download distribution folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish auth library
        run: npm publish ./dist/auth --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
